<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.smartparking</groupId>
  <artifactId>smart-parking-management-system</artifactId>
  <version>1.0.0</version>
  <packaging>pom</packaging>
  <modules>
    <module>eureka-server</module>
    <module>config-server</module>
    <module>api-gateway</module>
    <module>user-service</module>
    <module>vehicle-service</module>
    <module>parking-service</module>
    <module>payment-service</module>
  </modules>
</project>
